### ISSUE TITLE
Token on Github

### ISSUE THREAD

**Issue by bsantosh909** [MichaelM3/discord-bot-js2#1]
Oops you accidentally put your token on github, before any spammer finds it out and spam with your bot reset it as soon as possible, and **Do not** put it again on github.

[Learn how to avoid putting tokens on github](https://anidiots.guide/other-guides/using-git-to-share-and-update-code#initialization-and-gitignore)

**Comment by MichaelM3** [comment]
changed the token and used that one as an example
